# Generated by Django 3.0.2 on 2020-03-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_type', models.CharField(choices=[('1', 'Empty'), ('2', 'Extra')], max_length=1)),
                ('item', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('A', 'Food'), ('B', 'Homegoods'), ('C', 'Pets'), ('D', 'Kids'), ('E', 'Lawn'), ('F', 'Services'), ('G', 'Other')], max_length=1)),
                ('fulfilled', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
