# Generated by Django 3.0.2 on 2020-03-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField()),
                ('user1_name', models.CharField(max_length=50)),
                ('user2_id', models.IntegerField()),
                ('user2_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('cups_filled', models.IntegerField(default=0)),
                ('chats', models.ManyToManyField(to='main_app.Chat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=160)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('zip', models.IntegerField(default=0)),
                ('fulfilled_by_profile_id', models.IntegerField(default=0)),
                ('cup_type', models.CharField(choices=[('1', 'Empty'), ('2', 'Extra')], max_length=1)),
                ('item', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('A', 'Food'), ('B', 'Homegoods'), ('C', 'Pets'), ('D', 'Kids'), ('E', 'Lawn'), ('F', 'Services'), ('G', 'Other')], max_length=1)),
                ('fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
