# Generated by Django 3.0.2 on 2020-03-23 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField()),
                ('user1_name', models.CharField(max_length=50)),
                ('user2_id', models.IntegerField()),
                ('user2_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cup',
            name='owner',
        ),
        migrations.AddField(
            model_name='cup',
            name='fulfilled_by_profile_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cup',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('cups_filled', models.IntegerField()),
                ('chats', models.ManyToManyField(to='main_app.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=160)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_id', models.IntegerField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Chat')),
            ],
        ),
        migrations.AddField(
            model_name='cup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.User_Profile'),
        ),
    ]
