# Generated by Django 3.0.2 on 2020-03-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
