# Generated by Django 3.0.2 on 2020-03-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200324_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Cup')),
            ],
        ),
    ]
