# Generated by Django 3.0.2 on 2020-03-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
